project:
  type: website

website:
  title: "Fondata, LLC"
  navbar:
    title: "Fondata"
    background: turquoise
    foreground: black
    search: true
    left:
      - text: "Home"
        href: index.qmd  
      - usecases.qmd
      - about.qmd
  margin-header: |
     ![](/fdlogo.png)

format: 
  html:
    anchor-sections: true
    theme:
      - yeti
      - brand
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 3
    include-in-header:
      - text: |
          <style>
          .text-font {
            font-family: "Courier New", monospace; 
          }
          </style>




