---
title: "About Us"
about:
    template: trestles

---

## *Meet our founders.*   

We are a team of seasoned applied researchers, data scientists and academics, with experience in optimization, decision analysis, Bayes networks, statistics, and organizational behavior. 



### John Mark Agosta

John Mark Agosta has a long and varied applied research career in the Bay Area that extends back over 30 years, to the early days of AI. Most recently he spent eight years with Microsoft, as part of the Azure Data AI Co-innovation Engineering Team. He's held positions at SRI International, Toyota ITC, and Intel Research, interspersed with stints at several startups, during which he's written over 30 peer-reviewed publications and 6 accepted patents.  He founded the Bayesian Applications Workshop in 2002 that accompanies the Uncertainty in AI conference, and was awarded a Business Fellowship at the Santa Fe Institute in 2007. He holds a Bachelor's in Physics from Yale University, a Master's in Science Policy from George Washington University, and a PhD in Management Science and Engineering from Stanford University. 

Email: [johnmark "dot" agosta "at" fondata.ai](<johnmark.agosta@fondata.ai>)

[Publications](http://johnmarkagosta.com/jma_publications.html)

[LinkedIn profile](https://www.linkedin.com/in/john-mark-agosta/)

[Find me on Medium.com ](https://medium.com/@johnmark54)


### Dana Wang

Email: [dana "dot" wang "at" fondata.ai](<dana.wang@fondata.ai>)

## *Our collaborators* 

We work closely with other specialized software services and products companies, in areas related to our competencies.

[Win-Vector Labs](https://www.win-vector.com/) is a San Francisco based company specializing in data science. See their textbook [Practical Data Science with R](http://www.practicaldatascience.com/).

[Bayes Fusion](https://bayesfusion.com/) provides artificial intelligence modeling and machine learning software based on Bayes networks. 
