---
title: "Services"
about:
  template: trestles
---

## Forecasting Use Cases


### Financial forecasting, investor relations 

Industry: Enterprise software

Functional Group: Corporate CFO

Service:
Improved the accuracy and timeliness of financial forecasts used in quarterly stockholder reports by developing machine machine learning forecasting models. Resulted in improved shareholder communications and, by increasing efficiency, allowed CFO to allocate more time to strategic planning.


### Forecasting and Budgeting consolidation in the Cloud

Industry: Telecommunications

Functional group: Finance & Budgeting, multinational corporation

Service:
Moved forecasting and budgeting across functional groups to centralized data in the Cloud. Reduced overall workload and improved integration across subsidiaries. 

### Real-time Auto-Scaling Deployment Decision

Industry: Cloud software

Functional Group: Product Engineering

Service: 
Cloud service provider presented problem - customer website failure under load -- and asked whether to implement auto-scaling - dynamic adjustment of computer resources based on predicted demand. Developed prediction models showing auto-scaling optimization offered potential savings to $500K/year. Client was advised _not_ to implement autoscaling after further analysis of alternatives showed that ROI did not justify auto-scaling.

----

## Supply Chain Use Cases

### Real-time stock management: Estimating resources on-hand to meet random “walk-in” demand

Industry: Fast food

Functional Group: CTO 

Service: 
Client asked -- How many items should be ready-made? Too many - goods will be cold and wasted. Too few - lost revenue. Built a real time prediction model that trades off lost revenue with cost of discarded goods, to maximize profit.

### Sizing Seasonal Agricultural Product Shipping Requirements 

Industry: Freight Transportation Arrangement Industry 

Functional Group: Operations

Service: 
Forecasted customer demand by analyzing historical data on freight category, destination, and quantity. Client used forecast to match suppliers with customers in ship provisioning, maximizing utilization by reducing the number of freight transportation vessels. 

### Durable goods yield management to free up inventory capacity

Industry: Consumer Electronics,  Computer Hardware

Functional Group: Finance & Accounting Operations

Service: 
Revenue optimization by yield management to trade off forecasted revenue with inventory holding opportunity costs. Generated pricing markdown models by estimating product price elasticity that was used by client to trade off prices and quotas for existing stock, with freeing up inventory of older units and allowing room for new ones.

### Simulations of Electronic Health Records histories for Hospital management 

Industry: Healthcare

Functional Group: Hospital Finance and Strategic Planning

Service: Estimating hospital bed capacity needs, e.g. number of hospital beds, by detailed simulation of population health trends. Factored in demographics, predicted disease prevalence, and seasonal trends to manage hospital budgets and improve health outcomes.

----
## Root-cause Analysis Use Cases

### Semiconductor Fab Root cause fault analysis

Industry: Semiconductor manufacturing (fabrication plant)

Functional Group: Lean Manufacturing Operations

Service: 
Piloted a causal model for ranking the source of equipment faults by their probability. Built an interactive intelligent diagnostic model that codified the knowledge of repair experts, resulting in reduced level of expertise needed. Novel AI approach for on-the-fly model adjustment and learning during diagnostic sessions. Pilot deployment reduced down time, reducing bottlenecks, and increasing throughput. Predicted revenue estimated to be a few million dollars per year. 

### Diagnosing "OnTime and In Full" (OTIF) Failure Root Causes

Industry: Food service disposable and packaging, MNC

Functional Group: Corporate Accounting

Service: 
Developed a model from existing production data to predict OTIF that revealed that OTIF failures did _not_ originate in production.  Existing production scheduling was driven to avoid presumed shortages in output, resulting in excess inventory sitting in warehouses. Based on exploratory analyses advised the firm to adopt JIT (Just-In-Time manufacturing) to optimize inventory management. 

Identified the true source of inefficiencies in production management. Client assumed OTIF failures originated in production. Developed a model from existing production data to predict OTIF that indicated otherwise. Problem was excessive inventory sitting in warehouses. Based on exploratory analyses, advised the firm to adopt JIT (Just-In-Time manufacturing) to optimize inventory management, saving holding costs."

----
